import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import ReservationForm from '../containers/reservation-form';

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Feelo - new reservation</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
					rel="stylesheet"
					integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
					crossOrigin="anonymous"
				/>
				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"
				/>
			</Head>

			<main className={styles.main}>
				<h1>Feelo - new customer reservation</h1>
				<div className="container">
					<ReservationForm />
				</div>
			</main>
		</div>
	);
};

export default Home;
